name: CI for OTM tiler build

on: push

jobs:
  ci:
    name: Trigger otm-cluster build
    runs-on: ubuntu-latest
    steps:
      - name: Clone otm-cluster
        run: |
          mkdir -p ./src 
          cd ./src
          git clone https://${{ secrets.ACCESS_TOKEN }}@github.com/OpenTreeMap/otm-cluster.git

      - name: Generate commit-sha.txt
        run: echo "${GITHUB_REF##*/}-${GITHUB_SHA:0:7}" >> build/otm-tiler/commit-sha.txt

      - name: Commit files
        run: |
          git commit -a -m "Trigger tiler build"

      - name: Push changes to otm-cluster
        uses: ad-m/github-push-action@master
        with:
          force_with_lease: true
