name: CI for OTM tiler build

on: push

jobs:
  ci:
    name: Trigger otm-cluster build
    runs-on: ubuntu-latest
    steps:
      - name: Clone otm-cluster
        run: |
          mkdir -p ./src 
          cd ./src
          git clone https://${{ secrets.ACCESS_TOKEN }}@github.com/OpenTreeMap/otm-cluster.git

      - name: Generate commit-sha.txt
        run: |
          ls -la
          echo "${GITHUB_REF##*/}-${GITHUB_SHA:0:7}" >> src/build/otm-tiler/commit-sha.txt

      - name: Commit an push files
        run: |
          cd src
          git commit -a -m "Trigger tiler build"
          git push
